# Generated by Django 3.2.13 on 2022-05-24 08:39

import auth_.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mainuser',
            managers=[
                ('objects', auth_.models.MainUserManager()),
            ],
        ),
    ]
